---
- name: initialize application via composer.phar
  become_user: vagrant
  command: creates={{ APPDIR }}/
    /vagrant/composer.phar create-project --no-interaction --quiet symfony/framework-standard-edition {{ APPDIR }}
