---
- name: Add environment variables for app
  template: src=environment.j2 dest=/etc/environment

- name: create Apache VirtualHost for app
  template: src=apache2.vhost.j2 dest=/etc/apache2/sites-available/{{ appname }}.conf
  notify:
    restart Apache

# - name: add FastCGI worker pool
#   template: src=php-fpm-pool.conf.j2 dest=/etc/php/7.0/fpm/pool.d/{{ appname }}.conf
#   notify:
#     restart PHP70-FPM

- name: enable Apache VirtualHost for app
  command: creates=/etc/apache2/sites-enabled/{{ appname }}.conf
    a2ensite {{ appname }}
  notify:
    restart Apache
