---
- name: Ensure apt-transport-https is installed.
  apt: name=apt-transport-https state=present

- name: Import the NodeSource GPG key into apt
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add NodeSource repositories for Node.js.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_8.x jessie main"
    - "deb-src https://deb.nodesource.com/node_8.x jessie main"

- name: Install NodeJs
  apt: name=nodejs update_cache=yes

- name: Ensure Node.js and npm are installed.
  apt: "name=nodejs=8.* state=present"

- name: Add global packages
  npm: "name={{ item }} state=present global=yes"
  with_items:
    - jshint
    - gulp
